"use client"
import * as React from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
type Customer = { id: string; name: string | null; email: string; tags: string | null; notes: string | null; segment: string | null; status: string; createdAt: string | Date; orderCount: number; totalSpent: number }
function Row({ customer }: { customer: Customer }) { const router = useRouter(); const [tags, setTags] = React.useState(customer.tags ?? ""); const [notes, setNotes] = React.useState(customer.notes ?? ""); const [segment, setSegment] = React.useState(customer.segment ?? ""); async function save() { const response = await fetch(`/api/admin/customers/${customer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tags, notes, segment }) }); if (response.ok) { toast.success("Customer updated"); router.refresh() } else toast.error("Update failed") } return <Card><CardContent className="grid gap-4 pt-6 lg:grid-cols-[1.2fr_.6fr_1fr_1.5fr_auto]"><div><p className="font-medium">{customer.name || "Unnamed customer"}</p><p className="text-sm text-muted-foreground">{customer.email}</p><p className="mt-1 text-xs text-muted-foreground">{customer.orderCount} orders · ₦{customer.totalSpent.toLocaleString()}</p></div><div><Label>Segment</Label><Input value={segment} onChange={(e) => setSegment(e.target.value)} placeholder="VIP" /></div><div><Label>Tags</Label><Input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="vip, wholesale" /></div><div><Label>Private notes</Label><Textarea rows={2} value={notes} onChange={(e) => setNotes(e.target.value)} /></div><Button className="self-end" onClick={save}>Save</Button></CardContent></Card> }
export function CustomerManager({ customers, query, segment }: { customers: Customer[]; query: string; segment: string }) { return <div className="space-y-6"><div><h1 className="font-serif text-2xl font-semibold">Customers</h1><p className="text-muted-foreground">Real customer records, order value, tags, segments, and private notes.</p></div><form className="flex gap-3"><Input name="q" defaultValue={query} placeholder="Search name, email, or tags" /><Input name="segment" defaultValue={segment} placeholder="Segment" className="max-w-48" /><Button>Filter</Button></form>{customers.length ? customers.map((customer) => <Row key={customer.id} customer={customer} />) : <Card><CardContent className="py-10 text-center text-muted-foreground">No matching customers.</CardContent></Card>}</div> }
